package builder

import (
	"fmt"
	"strings"
)

// Each builder renders a hardened Dockerfile. The operator's install/build commands
// are sanitized to a single line (shellLine) so they can't inject extra directives;
// images run as a non-root user by default. These templates are sane starting points
// — an operator with an unusual build uses language: generic.

// --- node ---

type nodeBuilder struct{}

func (nodeBuilder) Name() string                  { return "node" }
func (nodeBuilder) Detect(f map[string]bool) bool { return f["package.json"] }
func (nodeBuilder) Dockerfile(s Spec) (string, error) {
	ver, err := version(s.Version, "20")
	if err != nil {
		return "", err
	}
	base := fmt.Sprintf("node:%s-alpine", ver)
	pkgs, err := packageLine("apk", s.Packages)
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", orDefault(s.Install, "npm install"))
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	cmd, err := cmdLine(s.Start)
	if err != nil {
		return "", err
	}
	lines := []string{
		"# generated by Helmsman — do not edit",
		"FROM " + base + " AS build",
		"WORKDIR /app",
		pkgs,
	}
	// Strip dev dependencies from the shipped image when installing with npm (the
	// default) — the build stage needs them, the runtime stage doesn't.
	prune := ""
	if strings.HasPrefix(install, "npm") {
		prune = "RUN npm prune --omit=dev"
	}
	lines = append(lines, envs...)
	lines = append(lines,
		// Copy manifests + lockfiles first so the install layer caches until they
		// change (a source-only edit won't re-run the install).
		"COPY package*.json ./",
		"RUN "+install,
		"COPY . .",
		runIf(build),
		prune,
		"FROM "+base+" AS run",
		"WORKDIR /app",
		"COPY --from=build /app /app",
	)
	lines = append(lines, nonrootIf(s.Nonroot, nonrootAlpine())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- python ---

type pythonBuilder struct{}

func (pythonBuilder) Name() string { return "python" }
func (pythonBuilder) Detect(f map[string]bool) bool {
	return f["requirements.txt"] || f["pyproject.toml"] || f["Pipfile"]
}
func (pythonBuilder) Dockerfile(s Spec) (string, error) {
	ver, err := version(s.Version, "3.12")
	if err != nil {
		return "", err
	}
	base := fmt.Sprintf("python:%s-slim", ver) // debian slim: best wheel compatibility
	pkgs, err := packageLine("apt", s.Packages)
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", orDefault(s.Install, "pip install --no-cache-dir -r requirements.txt"))
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	cmd, err := cmdLine(s.Start)
	if err != nil {
		return "", err
	}
	lines := []string{
		"# generated by Helmsman — do not edit",
		"FROM " + base,
		"WORKDIR /app",
		"ENV PYTHONUNBUFFERED=1 PIP_DISABLE_PIP_VERSION_CHECK=1",
		pkgs,
	}
	lines = append(lines, envs...)
	lines = append(lines, "COPY . .", "RUN "+install, runIf(build))
	lines = append(lines, nonrootIf(s.Nonroot, nonrootDebian())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- go ---

type goBuilder struct{}

func (goBuilder) Name() string                  { return "go" }
func (goBuilder) Detect(f map[string]bool) bool { return f["go.mod"] }
func (goBuilder) Dockerfile(s Spec) (string, error) {
	ver, err := version(s.Version, "1.23")
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", orDefault(s.Install, "go mod download"))
	if err != nil {
		return "", err
	}
	// CGO off → a static binary that runs on a tiny base.
	build, err := shellLine("build.build", orDefault(s.Build, "CGO_ENABLED=0 go build -o /out/app ./..."))
	if err != nil {
		return "", err
	}
	cmd := `CMD ["/app/app"]`
	if len(s.Start) > 0 {
		if cmd, err = cmdLine(s.Start); err != nil {
			return "", err
		}
	}
	lines := []string{
		"# generated by Helmsman — do not edit",
		fmt.Sprintf("FROM golang:%s-alpine AS build", ver),
		"WORKDIR /app",
	}
	lines = append(lines, envs...)
	lines = append(lines,
		"COPY . .",
		"RUN "+install,
		"RUN "+build,
		"FROM alpine:3",
		"WORKDIR /app",
		"RUN apk add --no-cache ca-certificates",
		"COPY --from=build /out/app /app/app",
	)
	lines = append(lines, nonrootIf(s.Nonroot, nonrootAlpine())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- ruby ---

type rubyBuilder struct{}

func (rubyBuilder) Name() string                  { return "ruby" }
func (rubyBuilder) Detect(f map[string]bool) bool { return f["Gemfile"] }
func (rubyBuilder) Dockerfile(s Spec) (string, error) {
	ver, err := version(s.Version, "3.3")
	if err != nil {
		return "", err
	}
	base := fmt.Sprintf("ruby:%s-alpine", ver)
	pkgs, err := packageLine("apk", s.Packages)
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", orDefault(s.Install, "bundle install"))
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	cmd, err := cmdLine(s.Start)
	if err != nil {
		return "", err
	}
	lines := []string{"# generated by Helmsman — do not edit", "FROM " + base, "WORKDIR /app", pkgs}
	// Skip development/test gems in the shipped image.
	lines = append(lines, `ENV BUNDLE_WITHOUT="development:test"`)
	lines = append(lines, envs...)
	lines = append(lines, "COPY . .", "RUN "+install, runIf(build))
	lines = append(lines, nonrootIf(s.Nonroot, nonrootAlpine())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- php (apache; mod_php serves HTTP on :80, apache drops to www-data) ---

type phpBuilder struct{}

func (phpBuilder) Name() string                  { return "php" }
func (phpBuilder) Detect(f map[string]bool) bool { return f["composer.json"] || f["index.php"] }
func (phpBuilder) Dockerfile(s Spec) (string, error) {
	ver, err := version(s.Version, "8.3")
	if err != nil {
		return "", err
	}
	pkgs, err := packageLine("apt", s.Packages)
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", s.Install) // e.g. composer install
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	lines := []string{
		"# generated by Helmsman — do not edit",
		fmt.Sprintf("FROM php:%s-apache", ver),
		"WORKDIR /var/www/html",
		pkgs,
		"COPY --from=composer:2 /usr/bin/composer /usr/bin/composer",
	}
	lines = append(lines, envs...)
	lines = append(lines, "COPY . .", runIf(install), runIf(build))
	// apache starts as root and drops to www-data itself; an explicit USER would
	// break binding :80, so php is the documented exception to USER app.
	return join(lines...), nil
}

// --- static (nginx serving the repo, optional build step) ---

type staticBuilder struct{}

func (staticBuilder) Name() string                  { return "static" }
func (staticBuilder) Detect(f map[string]bool) bool { return f["index.html"] }
func (staticBuilder) Dockerfile(s Spec) (string, error) {
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", s.Install)
	if err != nil {
		return "", err
	}
	// If there's a build step, run it in a node stage then serve ONLY the built
	// output (not the source + node_modules); else serve the repo as-is. The output
	// dir defaults to "dist" — set build.output for a different one (e.g. "build").
	if build != "" || install != "" {
		ver, _ := version(s.Version, "20")
		out := s.Output
		if out == "" {
			out = "dist"
		}
		lines := []string{
			"# generated by Helmsman — do not edit",
			fmt.Sprintf("FROM node:%s-alpine AS build", ver),
			"WORKDIR /app",
		}
		lines = append(lines, envs...)
		lines = append(lines, "COPY package*.json ./", runIf(install), "COPY . .", runIf(build),
			"FROM nginx:alpine",
			fmt.Sprintf("COPY --from=build /app/%s /usr/share/nginx/html", out),
		)
		return join(lines...), nil
	}
	return join(
		"# generated by Helmsman — do not edit",
		"FROM nginx:alpine",
		"COPY . /usr/share/nginx/html",
	), nil
}

// --- generic (best effort: operator's base + commands) ---

type genericBuilder struct{}

func (genericBuilder) Name() string                { return "generic" }
func (genericBuilder) Detect(map[string]bool) bool { return false } // never auto-selected
func (genericBuilder) Dockerfile(s Spec) (string, error) {
	if err := validImage(s.Base); err != nil {
		return "", err
	}
	pkgs, err := packageLine("apt", s.Packages) // best-effort: assume a debian-ish base
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", s.Install)
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	cmd, err := cmdLine(s.Start)
	if err != nil {
		return "", err
	}
	lines := []string{"# generated by Helmsman — do not edit", "FROM " + s.Base, "WORKDIR /app"}
	if pkgs != "" {
		lines = append(lines, pkgs)
	}
	lines = append(lines, envs...)
	lines = append(lines, "COPY . .", runIf(install), runIf(build))
	lines = append(lines, nonrootIf(s.Nonroot, nonrootDebian())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- small helpers ---

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

// runIf returns a RUN line for a non-empty command, else "".
func runIf(cmd string) string {
	if cmd == "" {
		return ""
	}
	return "RUN " + cmd
}

// nonrootIf returns the non-root snippet when enabled, else nil.
func nonrootIf(on bool, snippet []string) []string {
	if !on {
		return nil
	}
	return snippet
}
